name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Create .env file
        shell: cmd
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          echo SPOTIPY_CLIENT_ID="%SPOTIPY_CLIENT_ID%" >> neodeemer/.env
          echo SPOTIPY_CLIENT_SECRET="%SPOTIPY_CLIENT_SECRET%" >> neodeemer/.env
          echo YOUTUBE_API_KEY="%YOUTUBE_API_KEY%" >> neodeemer/.env

      - name: Download dependencies
        shell: cmd
        run: |
          python -m pip install pyinstaller==5.3
          python -m pip install -r neodeemer/requirements.txt
          curl -L https://downloads.fdossena.com/geth.php?r=mesa64-latest --output mesa.7z
          7z e mesa.7z opengl32.dll -o"neodeemer"

      - name: Remove unnecessary files
        shell: cmd
        run: |
          python -m pip uninstall -y pycryptodomex
          for /f "delims=" %%i in ('python -c "import sysconfig; print(sysconfig.get_path('purelib'))"') do cd /D "%%i"
          cd yt_dlp\extractor\
          mkdir ..\temp\
          move __init__.py ..\temp\ && move _extractors.py ..\temp\ && move adobepass.py ..\temp\ && move common.py ..\temp\ && move commonmistakes.py ..\temp\ && move commonprotocols.py ..\temp\ && move extractors.py ..\temp\ && move generic.py ..\temp\ && move lazy_extractors.py ..\temp\ && move openload.py ..\temp\ && move youtube.py ..\temp\
          del /S /Q *
          cd ..\temp\
          powershell -c "gc _extractors.py | select -first 26" > _extractors.py
          echo from .commonmistakes import CommonMistakesIE, UnicodeBOMIE >> _extractors.py
          echo from .commonprotocols import MmsIE, RtmpIE, ViewSourceIE >> _extractors.py
          echo from .generic import GenericIE >> _extractors.py
          move __init__.py ..\extractor\ && move _extractors.py ..\extractor\ && move adobepass.py ..\extractor\ && move common.py ..\extractor\ && move commonmistakes.py ..\extractor\ && move commonprotocols.py ..\extractor\ && move extractors.py ..\extractor\ && move generic.py ..\extractor\ && move lazy_extractors.py ..\extractor\ && move openload.py ..\extractor\ && move youtube.py ..\extractor\

      - name: Build with PyInstaller
        shell: cmd
        run: |
          cd neodeemer
          set KIVY_GL_BACKEND=angle_sdl2
          python -m PyInstaller neodeemer.spec

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: neodeemer/dist